version: '3.1'

services:

  redis:
    image: redis
    container_name: redis
    hostname: redis
    entrypoint:
      - redis-server
      - --requirepass
      - "123456"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0:123456
    ports:
      - "8082:8081"
    depends_on:
      - redis

volumes:
   redis-data:
