language:    # 指明使用的语言
  - go 

go: 
  - master   # 默认使用最新版本

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)